import { signIn, signOut, useSession } from "next-auth/react";
import { Html } from "next/document";
import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";
import Body from "~/components/Body";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Yummy Bites</title>
        <meta
          name="yummy bites order tracking web app"
          content="Generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header></Header>
        <Body></Body>
      </main>
    </>
  );
}
